#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=4,walltime=00:10:00

set -e
set -x

singularity exec -e docker://brainlife/dipy:1.1.1 python3 wmc2labels.py

mkdir -p output
mv index.csv output
mv names.csv output

echo "All done!"